# Site settings
title: Splathon公式ページ
description: "非公式IT企業対抗Splatoon大会『Splathon（スプラソン）』の公式ページです。"
baseurl: ""
url: "https://www.splathon.ink"
github_username: splathon
ga_tracking_id: UA-71773267-1

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - bin
timezone: Asia/Tokyo
